// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASStAcU8hrh2ICCCm4ARI6CehEUDbL9GY',
    appId: '1:149431166595:web:abe2c114c0d9db39365db6',
    messagingSenderId: '149431166595',
    projectId: 'esp32demo-fcad6',
    authDomain: 'esp32demo-fcad6.firebaseapp.com',
    databaseURL: 'https://esp32demo-fcad6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32demo-fcad6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPUQJN1yjyO-tKgYYy-JLpgdMOL3C1Q8g',
    appId: '1:149431166595:android:a9ad210c58effc28365db6',
    messagingSenderId: '149431166595',
    projectId: 'esp32demo-fcad6',
    databaseURL: 'https://esp32demo-fcad6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32demo-fcad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuMYpnokQJUVjPwc3iqLritU-dix7SgS4',
    appId: '1:149431166595:ios:ea41bdb5315dffef365db6',
    messagingSenderId: '149431166595',
    projectId: 'esp32demo-fcad6',
    databaseURL: 'https://esp32demo-fcad6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32demo-fcad6.appspot.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuMYpnokQJUVjPwc3iqLritU-dix7SgS4',
    appId: '1:149431166595:ios:88c4805b51fd9d9a365db6',
    messagingSenderId: '149431166595',
    projectId: 'esp32demo-fcad6',
    databaseURL: 'https://esp32demo-fcad6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'esp32demo-fcad6.appspot.com',
    iosBundleId: 'com.example.flutterAuth.RunnerTests',
  );
}
